[features]
seeds = false
[programs.devnet]
mugs_marketplace = "Gaprzf3E59Es31MGcRDychJu1TY55hYo9zS7B1JMGnPS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=4401b929-7687-43b5-ab0b-77a34de621e9"
# cluster = "devnet"
wallet = "./local-creator.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
