[features]
seeds = false
[programs.devnet]
mugs_marketplace = "D8MwjwdpEEPN1MbEQJRn2hgzZAFtXDV5h7pYHREQeMrU"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "https://rpc-devnet.hellomoon.io/6a21468a-dd17-4158-a684-29d180654392"
# cluster = "devnet"
wallet = "./local-creator.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
